### ISSUE TITLE
Icons break nested item padding in Nav

### ISSUE THREAD

**Issue by tabathadelane** [newrelic/gatsby-theme-newrelic#500]
## Description

If the Nav is using icons, like on the [Developer site](https://github.com/newrelic/developer-website), the padding logic stops working on the nested items. 

## Steps to Reproduce

```
- title: Explore docs
  icon: nr-book
  pages:
    - title: New Relic One CLI
      url: '/explore-docs/nr1-cli'
      pages:
        - title: Common commands
          url: '/explore-docs/nr1-common'
        - title: Config commands
          url: '/explore-docs/nr1-config'
        - title: Nerdpack commands
          url: '/explore-docs/nr1-nerdpack'
        - title: Subscription commands
          url: '/explore-docs/nr1-subscription'
        - title: Plugin commands
          url: '/explore-docs/nr1-plugins'
        - title: Catalog commands
          url: '/explore-docs/nr1-catalog'
    - title: New Relic CLI
      url: '/explore-docs/newrelic-cli'
```

In this example, the nested `pages` menu won't have the correct padding. When I remove `icon` from the code, the padding works. 

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour

Expect the padding to work with icons.

[NOTE]: # ( Tell us what you expected to happen. )

## Your Environment

Chrome on Mac

## Additional context

With Icons, the items under `New Relic One CLI` are not nested.
<img width="263" alt="Screen Shot 2021-10-13 at 10 18 25 AM" src="https://user-images.githubusercontent.com/47728020/137182084-45c0ecd3-8e3d-4ecf-a647-0f0e4c6fb0e7.png">

When the icon code is removed, the padding works as expected. 
<img width="263" alt="Screen Shot 2021-10-13 at 10 18 47 AM" src="https://user-images.githubusercontent.com/47728020/137182088-8980578f-ec8e-44c7-9006-e217a0f01fce.png">

Related to https://github.com/newrelic/developer-website/issues/1740
